package com.sinensia.helloselenium;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class HelloFirefoxImdbTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeAll
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterAll
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void helloImdb() {
    // Test name: HelloImdb
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.imdb.com/");
    // 2 | setWindowSize | 1853x951 | 
    driver.manage().window().setSize(new Dimension(1853, 951));
    // 3 | click | id=suggestion-search | 
    driver.findElement(By.id("suggestion-search")).click();
    // 4 | type | id=suggestion-search | The Flash
    driver.findElement(By.id("suggestion-search")).sendKeys("The Flash");
    // 5 | sendKeys | id=suggestion-search | ${KEY_ENTER}
    driver.findElement(By.id("suggestion-search")).sendKeys(Keys.ENTER);
    // 6 | click | linkText=The Flash |
    // 6.5
    WebElement we;
    we = new WebDriverWait(driver, 45)
            .until(ExpectedConditions.elementToBeClickable(By.linkText("The Flash")));

    driver.findElement(By.linkText("The Flash")).click();
    // 6.5
    we = new WebDriverWait(driver, 45)
            .until(ExpectedConditions.elementToBeClickable(By.linkText("Trivia")));
    // 7 | assertText xpath=//h1 | The Flash
    assertThat(driver.findElement(By.xpath("//h1")).getText(), is("The Flash"));
  }
}
